# cache vendor folder between builds
cache:
  paths:
    - vendor/

stages:
  - test

.phpunit:
  image: php:latest
  script:
    - apt-get update -yqq
    - apt-get install git zip -yqq
    # Install composer
    - curl -sS https://getcomposer.org/installer | php
    # Install all project dependencies
    - php composer.phar install
    - vendor/bin/phpunit tests --log-junit report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

php 7.1:
  extends: .phpunit
  image: php:7.1

php 7.2:
  extends: .phpunit
  image: php:7.2

php 7.3:
  extends: .phpunit
  image: php:7.3

php 7.4:
  extends: .phpunit
  image: php:7.4

php 8.0:
  extends: .phpunit
  image: php:8.0

php 8.1:
  extends: .phpunit
  image: php:8.1